function_overloading: function_overloading.o
	g++ -o function_overloading function_overloading.o
function_overloading.o: function_overloading.cc
	g++ -c function_overloading.cc
clean:
	rm function_overloading function_overloading.o